### ISSUE TITLE
Rename BMC

### ISSUE THREAD

**Issue by johannesgiersdorf** [theogf/BayesianQuadrature.jl#10]
I would suggest to rename BMC.
`Bayesian Monte Carlo, the simplest approach for Bayesian Quadrature. Assumes that the prior is Gaussian and that the integrand is as well`
https://github.com/theogf/BayesianQuadrature.jl/blob/d621e84566cbcafa7cbe13a6036873479b19471d/src/integrators/bmc.jl#LL1-L7

It is true that it is motivated by the example from the paper and it should be referenced (I suggest in the readme). It is misleading to use the name BMC in the quadrature part (BMC refers more on how to sample the states and than use BQ).

I would refer instead to the distribution (or even kernel-distribution pair), where the distribution is the one we are importance re-weighting "against" (e.g. Gaussian in the simple case (SE kernel - Gaussian)).

See also 4.2  Tractable and Intractable Kernel Means
`Briol, F. X., Oates, C. J., Girolami, M., Osborne, M. A., & Sejdinovic, D. (2019). Probabilistic integration: A role in statistical computation?. Statistical Science, 34(1), 1-22.`

Remark: The idea is having kernel-distribution pairs with a closed form kernel mean.
the case (SE kernel - Gaussian) is called Bayes–Hermite quadrature
`O’Hagan, A. (1991).  Bayes–Hermite quadrature.J. Statist. Plann. Inference, 29:245–260.`

**Comment by theogf** [comment]
That's a good point! Naming things is always complicated...

But here is my current thought about how to split things (updated from #1)
- The model (a subtype of `AbstractMCMC.Model`) which contains the prior and the integrand, the reweighting can simply happen in here (by dispatching the `prior` and `integrand` function)
- The sampling, i.e how are samples selected)
- The integration are we using bayesian quadrature or is there some more fancyness happening (Variational BQ etc)
- The kernel means, we should have a generic implementation relying on either MC or Quadrature, maybe table being reused for weighting? As well as specific implementations for tractable kernels.

Would you have a suggestion for a better name?

**Comment by johannesgiersdorf** [comment]
bayesquad -> bayesianMCMC (Bayesian Markov Chain Monte Carlo)
BMC -> BH (Bayes-Hermite) < TKM (Tractable Kernel Means) < AbstractIntegrator
