### ISSUE TITLE
log integrand in BayesModel

### ISSUE THREAD

**Issue by johannesgiersdorf** [theogf/BayesianQuadrature.jl#13]
Using the logarithm of the integrand in the `BayesModel` provides a more stable way of computing functions regarding the integrand (e.g. `logjoint`)

**Comment by johannesgiersdorf** [comment]
Using the logarithm of the integrand only works with positive integrands. My suggestion would be to use a separate model Type for positive Integrand (which works directly with the logarithm of the integrand) for example `BayesLogModel` and one model that can take any integrand.

**Comment by theogf** [comment]
But by definition for a BayesModel the integrand needs to be positive!

**Comment by johannesgiersdorf** [comment]
Right, then we could add a Type `Model` or something similar for the general case.

**Comment by theogf** [comment]
Yep! That sounds good!
